image:
  repository: your-docker-repo/sample-web-app
  tag: latest

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - /

resources: {}
  
nodeSelector: {}

tolerations: []

affinity: {}

env:
  NODE_ENV: stage
  PORT: "3000"