apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sample-web-app.fullname" . }}
  labels:
    {{- include "sample-web-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include "sample-web-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sample-web-app.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        {{- if .Values.imagePullSecrets }}
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
        {{- end }}
      containers:
        - name: {{ include "sample-web-app.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.env.PORT | default "3000" | int }}
          env:
            - name: NODE_ENV
              value: {{ .Values.env.NODE_ENV | quote }}
            - name: PORT
              value: "{{ .Values.service.port }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}